! gfortran -O2 -Wall -Wextra -o test-rnd-parallel test-rnd-parallel.F90 test-rnd.f90 -fopenmp -lrt
! Runtime checks: gfortran -O2 -Wall -Wextra -fsanitize=undefined -o test-rnd-parallel test-rnd-parallel.F90 test-rnd.f90 -fopenmp -lrt
! ./test-rnd-run >(head -c 12 | xxd -b -g 0 -c 3 1>&2) | head -20
! ./test-rnd-run >(head -c 12 | xxd -b -g 0 -c 3 1>&2) >/dev/null
! ./test-rnd-run >(head -c1M | md5sum)
! timeout 10 ./test-rnd-run >(pv >/dev/null)
! time ./test-rnd-run >(PractRand-RNG_test stdin -tlmax 4G -multithreaded)

program test_rnd_run
  use omp_lib
  use types_const, only: dp, missing
  use test_rnd
  implicit none

  integer                         :: num_args
  character(len=1024)             :: filename, progname, bytes_requested_string
!  integer, parameter              :: k4b=selected_int_kind(9)
  integer, parameter              :: size=4*1024*1024
  integer(kind=4)                 :: j
  integer(kind=1), dimension(:), allocatable :: d
  type(t_rnd_state), dimension(:), allocatable :: s
  real(dp)                        :: x, y
  integer(kind=4)                 :: i, k, error, chunks, threads, tid
  integer(kind=8),dimension(2)    :: ccount, count_rate, count_max
  integer(kind=8)                 :: bytes_requested, steps, l

  num_args = command_argument_count()

  if (num_args /= 2) then
   print *, "Expecting two arguments"
   call get_command_argument(0, progname)
   print "(a10,a)", progname, "size(GiB) filename"
   print *, "          size(GiB)  ... How many GiB to generate. 0 means endless stream of random bytes"
   print *, "          filename   ... write random bytes to filename. Use process substitution in shell"
   print *, "                         to send output to another process"
   print "(a,a)", progname, "0 >(pv >/dev/null)"
   stop 1
  end if

  call get_command_argument(1, bytes_requested_string)
  read(bytes_requested_string,*)bytes_requested
  bytes_requested = bytes_requested * 1024 * 1024 * 1024

  call get_command_argument(2, filename)

  ! the return value of omp_get_max_chunks() is controlled by
  !   export OMP_NUM_THREADS=n
  threads=omp_get_max_threads()
  print *, "Threads: ", threads

  ! chunks has to be >= threads 
  chunks = 4
  if (threads>1) then
    chunks = threads + 1
  else
    chunks = 1
  end if  

  print *, "Chunks: ", chunks

  allocate( s(chunks), d(3*size*chunks), stat=error)
  if ( error /= 0 ) then
      print *, "Cannot allocate arrays."
      stop
  end if

  ! asynchronous='yes' breaks the order!
  open(file=filename, unit=8, access="stream",form="unformatted", action='write', asynchronous='no')

  call rnd_init(s)

  if (bytes_requested>0) then
    !ceiling integer division
    steps = ( bytes_requested + 3*size*chunks - 1 ) / (3*size*chunks)
  else
    steps = huge(steps)
  endif

  ! On Linux, link with -lrt to get nanosecond precision
  call system_clock(ccount(1), count_rate(1), count_max(1))

  !$omp parallel default(none) private(k,x,j,i,tid,l) shared(s,d,chunks,steps)
  do l=1,steps
    !$omp do ordered
    do k=1, chunks
      do i=(k-1)*size+1,k*size
        call ran1(s(k),x)
        j = INT(x*16777216,4)
        d(3*i-2) = INT(IBITS(j, 16, 8),1)
        d(3*i-1) = INT(IBITS(j, 8, 8),1)
        d(3*i)   = INT(IBITS(j, 0, 8),1)
      end do
      !$omp ordered
      !print *,k, "chunk", d(3*(k-1)*size+1:3*k*size)
      !print *,"k",k,"thread_id",omp_get_thread_num()
      write(8,asynchronous="no") d(3*(k-1)*size+1:3*k*size)
      !$omp end ordered
    end do
    !omp barrier
    !omp single
    !write(8,asynchronous="yes") d(1:3*size*chunks)
    !do k=1, chunks
    !  print *,k, "mmunk", d(3*(k-1)*size+1:3*k*size)
    !end do
    !omp end single
   end do
  !$omp end parallel


  close(8)

  call system_clock(ccount(2), count_rate(2), count_max(2))
  x = 3*size*chunks*steps / 1024.0D0 / 1024.0D0 / 1024.0D0
  y = (ccount(2)-ccount(1)) / 1000.0D0 / 1000.0D0 / 1000.0D0
  j = d(3*size*chunks)
  if (j<0) then
    j = 256 + j
  endif
  print *, "Generated ", x, "random GiB in ", y, "seconds, last generated byte is ", j
  x = x / y * 1024.0D0
  print *, x, "MiB/s"
end program test_rnd_run
